name: news_app_clean_architecture
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0

  cupertino_icons: ^1.0.2

  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.1
  get_it: ^7.2.0

  animate_do: ^3.0.2
  cached_network_image: ^3.0.0
  shimmer: ^2.0.0
  sqflite: ^2.0.3+1
  shared_preferences: ^2.0.15
  image_picker: ^0.8.6+1
  lottie: ^1.4.2
  page_transition: ^2.0.9
  smooth_page_indicator: ^1.0.1
  device_preview:  
  auto_size_text: ^3.0.0
  google_sign_in: ^6.0.2
  firebase_auth: ^4.1.2
  firebase_core: ^2.3.0
  flutter_facebook_auth: ^5.0.7
  email_validator: ^2.0.1
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  translator: ^0.1.7
  app_settings:
  url_launcher:
  hive:
  hive_flutter:
  animated_text_kit:

dev_dependencies:
  hive_generator:
  build_runner:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation_image/on_boarding/onBoarding1.json
    - assets/map.json

  fonts:
    - family: poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf

    - family: arabic
      fonts:
        - asset: assets/Fonts/Harmattan-Regular.ttf

    # see https://flutter.dev/custom-fonts/#from-packages
